Models/ManagerBuilding.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Accommodation.Models
{
    public class ManagerBuilding
    {
        [Key]
        public int ManagerBuildingId { get; set; }
        public int ManagerId { get; set; }
        public int BuildingId { get; set; }
        public virtual Building Building { get; set; }
        public virtual Manager Manager { get; set; }
    }
}

Controllers/ManagerBuildingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Accommodation.Models;
using Accommodation.Services.Interface;
using Microsoft.AspNet.Identity;

namespace Accommodation.Controllers
{
    public class ManagerBuildingsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private IManagerBuildingService _managerBuildingService;

        public ManagerBuildingsController(IManagerBuildingService managerBuildingService)
        {
            _managerBuildingService = managerBuildingService;
        }

        // GET: ManagerBuildings
        public ActionResult Index()
        {
            var managerBuildings = db.ManagerBuildings.Include(m => m.Building).Include(m => m.Manager);
            return View(managerBuildings.ToList());
        }

        // GET: ManagerBuildings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ManagerBuilding managerBuilding = db.ManagerBuildings.Find(id);
            if (managerBuilding == null)
            {
                return HttpNotFound();
            }
            return View(managerBuilding);
        }

        // GET: ManagerBuildings/Create
        public ActionResult Create()
        {
            var userName = User.Identity.GetUserName();
            ViewBag.BuildingId = new SelectList(db.buildings.Where(x=>x.OwnerEmail==userName), "BuildingId", "BuildingName");
            ViewBag.ManagerId = new SelectList(db.Managers.Where(x=>x.OwnerEmail==userName), "ManagerId", "FullName");
            return View();
        }

        // POST: ManagerBuildings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ManagerBuildingId,ManagerId,BuildingId")] ManagerBuilding managerBuilding)
        {
            var userName = User.Identity.GetUserName();
            if (ModelState.IsValid)
            {
                if (_managerBuildingService.ChceckIfExists(managerBuilding))
                {
                    ModelState.AddModelError("", "You can not add the same manager for the same building two times");
                    ViewBag.BuildingId = new SelectList(db.buildings.Where(x => x.OwnerEmail == userName), "BuildingId", "BuildingName", managerBuilding.BuildingId);
                    ViewBag.ManagerId = new SelectList(db.Managers.Where(x => x.OwnerEmail == userName), "ManagerId", "FullName", managerBuilding.ManagerId);
                    return View(managerBuilding);
                }
                else
                {
                    db.ManagerBuildings.Add(managerBuilding);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.BuildingId = new SelectList(db.buildings.Where(x=>x.OwnerEmail==userName), "BuildingId", "BuildingName", managerBuilding.BuildingId);
            ViewBag.ManagerId = new SelectList(db.Managers.Where(x=>x.OwnerEmail==userName), "ManagerId", "FullName", managerBuilding.ManagerId);
            return View(managerBuilding);
        }

        // GET: ManagerBuildings/Edit/5
        public ActionResult Edit(int? id)
        {
            var userName = User.Identity.GetUserName();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ManagerBuilding managerBuilding = db.ManagerBuildings.Find(id);
            if (managerBuilding == null)
            {
                return HttpNotFound();
            }
            ViewBag.BuildingId = new SelectList(db.buildings.Where(x=>x.OwnerEmail==userName), "BuildingId", "BuildingName", managerBuilding.BuildingId);
            ViewBag.ManagerId = new SelectList(db.Managers.Where(x=>x.OwnerEmail==userName), "ManagerId", "FullName", managerBuilding.ManagerId);
            return View(managerBuilding);
        }

        // POST: ManagerBuildings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ManagerBuildingId,ManagerId,BuildingId")] ManagerBuilding managerBuilding)
        {
            if (ModelState.IsValid)
            {
                db.Entry(managerBuilding).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BuildingId = new SelectList(db.buildings, "BuildingId", "BuildingName", managerBuilding.BuildingId);
            ViewBag.ManagerId = new SelectList(db.Managers, "ManagerId", "FullName", managerBuilding.ManagerId);
            return View(managerBuilding);
        }

        // GET: ManagerBuildings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ManagerBuilding managerBuilding = db.ManagerBuildings.Find(id);
            if (managerBuilding == null)
            {
                return HttpNotFound();
            }
            return View(managerBuilding);
        }

        // POST: ManagerBuildings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ManagerBuilding managerBuilding = db.ManagerBuildings.Find(id);
            db.ManagerBuildings.Remove(managerBuilding);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/ManagerBuildings/Create.cshtml
@model Accommodation.Models.ManagerBuilding

@{
    ViewBag.Title = "Create";
}

<h2>Assign Manager To Building</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @*<h4>ManagerBuilding</h4>*@
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ManagerId, "Manager Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ManagerId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ManagerId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BuildingId, "Building Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("BuildingId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.BuildingId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
            <a class="btn btn-default" href="@Url.Action("Index","ManagerBuildings")">
                <i class="fa fa-angle-left"></i>
                Back to List
            </a>
        </div>
    </div>
</div>
}

Views/ManagerBuildings/Delete.cshtml
@model Accommodation.Models.ManagerBuilding

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ManagerBuilding</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Building.BuildingName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Building.BuildingName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manager.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manager.FullName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/ManagerBuildings/Details.cshtml
@model Accommodation.Models.ManagerBuilding

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ManagerBuilding</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Building.BuildingName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Building.BuildingName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manager.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manager.FullName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ManagerBuildingId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/ManagerBuildings/Edit.cshtml
@model Accommodation.Models.ManagerBuilding

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ManagerBuilding</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ManagerBuildingId)

        <div class="form-group">
            @Html.LabelFor(model => model.ManagerId, "ManagerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ManagerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ManagerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BuildingId, "BuildingId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BuildingId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BuildingId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/ManagerBuildings/Index.cshtml
@model IEnumerable<Accommodation.Models.ManagerBuilding>

@{
    ViewBag.Title = "Index";
}

<h2>Building Managers</h2>
<a class="btn btn-default" href="@Url.Action("Create","ManagerBuildings")">
    <i class="fa fa-plus"></i>
    Assign Manager
</a>
<table class="table table-hover table-striped table-responsive" id="my_list">
    <thead>
        <tr class="table-header-row">
            <th>
                @Html.DisplayNameFor(model => model.Building.BuildingName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Manager.FullName)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Building.BuildingName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Manager.FullName)
                </td>
                <td>
                    <a href="@Url.Action("Details","ManagerBuildings", new { id=item.ManagerBuildingId })" rel="tooltip" title="View" class="btn btn-info btn-simple btn-xs"><i class="fa fa-eye"></i></a>
                    <a href="@Url.Action("Edit","ManagerBuildings", new { id=item.ManagerBuildingId})" rel="tooltip" title="Edit" class="btn btn-success btn-simple btn-xs"><i class="fa fa-edit"></i></a>
                    <a href="@Url.Action("Delete", "ManagerBuildings", new { id = item.ManagerBuildingId })" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-xs"><i class="fa fa-trash"></i></a>
                </td>
            </tr>
        }


    </tbody>
</table>
<script type="text/javascript">
    $('#my_list').dataTable(
         {
             dom: 'Bfrtip',
             lengthMenu: [
                 [10, 25, 50, -1],
                 ['10 rows', '25 rows', '50 rows', 'Show all']
             ],
             buttons: [
                 'pageLength', 'csv', 'pdf', 'print'
             ],
             language: { search: "" },
             select: true
         }
     );
     $(".dataTables_filter input").addClass("search-input");
     $(".dataTables_filter input").attr('placeholder', 'Search');
     $('#my_list')
         .removeClass('display')
         .addClass('table table-striped table-hover');</script>