Models/Owner.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;

namespace Accommodation.Models
{
    public class Owner
    {
        [Key]
        public int ownerID { get; set; }
        [Required]
        [RegularExpression(pattern: @"^[a-zA-Z''-'\s]{1,40}$", ErrorMessage = "Numbers and special characters are not allowed.")]
        [StringLength(maximumLength: 228, ErrorMessage = "First Name must be atleast 3 characters long", MinimumLength = 3)]
        [DisplayName("Full Name")]
        public string FullName { get; set; }
        [Required]
        [RegularExpression(pattern: @"^[a-zA-Z''-'\s]{1,40}$", ErrorMessage = "Numbers and special characters are not allowed.")]
        [StringLength(maximumLength: 228, ErrorMessage = "Last Name must be atleast 3 characters long", MinimumLength = 3)]
        [DisplayName("Last Name")]
        public string LastName { get; set; }
        [Display(Name = "Identity Number")]
        [MaxLength(13), MinLength(13)]
        public string IDNumber { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        [Required]
        [Display(Name = "Email")]
        [DataType(dataType: DataType.EmailAddress)]
        //[RegularExpression(pattern: @"^\w+[\w-\.]*\@\w+((-\w+)|(\w*))\.[a-z]{2,3}$", ErrorMessage = "Email not valid")]
        public string Email { get; set; }
        [Required]
        [Display(Name = "Phone Number")]
        [DataType(DataType.PhoneNumber)]
        //[RegularExpression(pattern: @"^\(?([0]{1})\)?[-. ]?([1-9]{1})[-. ]?([0-9]{8})$", ErrorMessage = "Entered Phone format is not valid.")]
        //[StringLength(maximumLength: 10, ErrorMessage = "SA Contact Number must be exactly 10 digits long", MinimumLength = 10)]
        public string Phone { get; set; }
        public string UserId { get; set; }
        [Display(Name = "Uploaded File")]
        public string FileName { get; set; }
        public byte[] FileContent { get; set; }
        [StringLength(128)]
        public string Nationality { get; set; }
        public string Gender { get; set; }
        [Display(Name = "Alternative Number")]    
        public string AltContactNumber { get; set; }
    }
}

Controllers/OwnersController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Accommodation.Models;
using Accommodation.Services.Implementation;
using Accommodation.Services.Interface;
using Microsoft.AspNet.Identity;
using PayFast;
using PayFast.AspNet;

namespace Accommodation.Controllers
{
    public class OwnersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        private ISubscriptionPriceService _subscriptionPriceService;


        public OwnersController(ApplicationUserManager userManager, ISubscriptionPriceService subscriptionPriceService)
        {
            _userManager = userManager;
            _subscriptionPriceService = subscriptionPriceService;

        }
        // GET: Owners
        public ActionResult Index()
        {
            var userName = User.Identity.GetUserName();
            var owners = db.owners.Where(x => x.Email == userName);
            return View(owners.ToList());
        }
        public ActionResult AdminIndex()
        {
            return View(db.owners.ToList());
        }
        public ActionResult Download(int? id)
        {
            MemoryStream ms = null;

            var item = db.owners.FirstOrDefault(x => x.ownerID == id);
            if (item != null)
            {
                ms = new MemoryStream(item.FileContent);
            }
            return new FileStreamResult(ms, item.FileName);


            //return RedirectToAction("Download");
        }



        [HttpPost]
        public ActionResult ViewPDF(int? id)
        {
            var r = db.owners.Find(id);
            //PDF pDF = db.PDFs.Find(id);
            string embed = "<object data=\"{0}\" type=\"application/pdf\" width=\"500px\" height=\"300px\">";
            embed += "If you are unable to view file, you can download from <a href = \"{0}\">here</a>";
            embed += " or download <a target = \"_blank\" href = \"http://get.adobe.com/reader/\">Adobe PDF Reader</a> to view the file.";
            embed += "</object>";
            TempData["Embed"] = string.Format(embed, VirtualPathUtility.ToAbsolute(r.FileName));

            return RedirectToAction("Index");
        }

        public ActionResult Approve(int? id)
        {
            Owner owner = db.owners.Where(p => p.ownerID == id).FirstOrDefault();
            if (owner.Status == "Approved" || owner.Status == "Rejected")
            {
                TempData["AlertMessage"] = "Th application has already been Rejected/Approved";
                return RedirectToAction("AdminIndex");
            }
            else
            {
                var amount = _subscriptionPriceService.GetSubscriptionPrices().Select(p => p.Price).Max();
                ApprovedOwnerss approvedOwnerss = new ApprovedOwnerss();
                approvedOwnerss.ownerID = owner.ownerID;
                approvedOwnerss.FullName = owner.FullName;
                approvedOwnerss.LastName = owner.LastName;
                approvedOwnerss.Email = owner.Email;
                approvedOwnerss.IDNumber = owner.IDNumber;
                approvedOwnerss.Phone = owner.Phone;
                approvedOwnerss.Type = owner.Type;
                approvedOwnerss.FileName = owner.FileName;
                approvedOwnerss.AltContactNumber = owner.AltContactNumber;
                approvedOwnerss.Status = "Approved";
                approvedOwnerss.Price = amount;
                db.ApprovedOwners.Add(approvedOwnerss);
                db.SaveChanges();
                //var userId = User.;
                //var nno = db.owners.ToList().Where(p => p.Email == approvedOwnerss.Email).Select(p => p.FullName).FirstOrDefault();
                //var user = db.owners.Find(owner.UserId);

                var mailTo = new List<MailAddress>();
                mailTo.Add(new MailAddress(owner.Email, owner.FullName));
                var body = $"Hello {owner.FullName}, Congratulations. We are glad to inform you that your application has been approved. You can now procced to adding your building details. You are required to pay the Subscription Fee in order for your building to be active to the Tenants <br/> Regards,<br/><br/> HomeLink <br/> .";

                Accommodation.Services.Implementation.EmailService emailService = new Accommodation.Services.Implementation.EmailService();
                emailService.SendEmail(new EmailContent()
                {
                    mailTo = mailTo,
                    mailCc = new List<MailAddress>(),
                    mailSubject = "Application Statement | Ref No.:" + owner.ownerID,
                    mailBody = body,
                    mailFooter = "<br/> Many Thanks, <br/> <b>Alliance</b>",
                    mailPriority = MailPriority.High,
                    mailAttachments = new List<Attachment>()

                });
                db.owners.Remove(owner);
                db.SaveChanges();
                //UserManager.AddToRole(user.Id, "Landlord");
                _userManager.AddToRole(owner.UserId, "Landlord");
                TempData["AlertMessage"] = $"{owner.FullName} has been successfully approved";

                return RedirectToAction("AdminIndex");
            }

        }
        public ActionResult Reject(int? id)
        {
            Owner owner = db.owners.Where(p => p.ownerID == id).FirstOrDefault();
            if (owner.Status == "Rejected" || owner.Status == "Approved")
            {
                TempData["AlertMessage"] = "Th application has already been Rejected";
                return RedirectToAction("AdminIndex");
            }
            else
            {
                owner.Status = "Rejected";
                db.Entry(owner).State = EntityState.Modified;
                db.SaveChanges();
                var mailTo = new List<MailAddress>();
                mailTo.Add(new MailAddress(owner.Email, owner.FullName));
                var body = $"Good Day {owner.FullName}, we apologize to inform you that your application has been rejected because your documentation(Title Deed) is incorrect.";

                Accommodation.Services.Implementation.EmailService emailService = new Accommodation.Services.Implementation.EmailService();
                emailService.SendEmail(new EmailContent()
                {
                    mailTo = mailTo,
                    mailCc = new List<MailAddress>(),
                    mailSubject = "Application Statement  | Ref No.:" + owner.ownerID,
                    mailBody = body,
                    mailFooter = "<br/> Many Thanks, <br/> <b>Alliance</b>",
                    mailPriority = MailPriority.High,
                    mailAttachments = new List<Attachment>()

                });
                TempData["AlertMessage"] = $"{owner.FullName} has been rejected";

                return RedirectToAction("AdminIndex");
            }
        }

        // GET: Owners/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Owner owner = db.owners.Find(id);
            if (owner == null)
            {
                return HttpNotFound();
            }
            return View(owner);
        }

        // GET: Owners/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Owners/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ownerID,FullName,LastName,IDNumber,Type,Email,Phone,Nationality,Gender,AltContactNumber")] Owner owner)
        {
            if (ModelState.IsValid)
            {
                db.owners.Add(owner);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(owner);
        }

        // GET: Owners/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Owner owner = db.owners.Find(id);
            if (owner == null)
            {
                return HttpNotFound();
            }
            return View(owner);
        }

        // POST: Owners/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ownerID,FullName,LastName,IDNumber,Type,Email,Phone,Nationality,Gender,AltContactNumber")] Owner owner)
        {
            if (ModelState.IsValid)
            {
                db.Entry(owner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(owner);
        }

        // GET: Owners/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Owner owner = db.owners.Find(id);
            if (owner == null)
            {
                return HttpNotFound();
            }
            return View(owner);
        }

        // POST: Owners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

Views/Owners/AdminIndex.cshtml
@model IEnumerable<Accommodation.Models.Owner>
@{
    ViewBag.Title = "Index";
    var message = TempData["AlertMessage"] ?? string.Empty;
}
<script>
    var msg = '@message';
    if (msg)
        alert(msg);
</script>
<h2 align="center">Landlord Applications</h2>
<br />
<table class="table table-hover table-striped table-responsive" id="my_list">
    <thead>
        <tr class="table-header-row">
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IDNumber)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.Type)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AltContactNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IDNumber)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AltContactNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FileName)
            </td>
            <td>
                @Html.ActionLink("Downlaod File", "DownLoadFile", new { id = item.ownerID })<br />
                <a href="@Url.Action("Approve", "Owners",new { id = item.ownerID })" onclick="return confirm('Are you sure you want to Approve, click Ok to Confirm, Or Cancel');" rel="tooltip" title="Approve" class="btn btn-success btn-simple btn-xs"><i class="fa fa-check-square-o"></i></a>
                <a href="@Url.Action("Reject", "Owners",new { id = item.ownerID })" onclick="return confirm('Are you sure you want to Reject, click Ok to Confirm, Or Cancel');" rel="tooltip" title="Reject" class="btn btn-danger btn-simple btn-xs"><i class="glyphicon glyphicon-remove"></i></a>
            </td>
        </tr>
        }

    </tbody>
</table>
 <script type="text/javascript">
    $('#my_list').dataTable(
         {
             dom: 'Bfrtip',
             lengthMenu: [
                 [10, 25, 50, -1],
                 ['10 rows', '25 rows', '50 rows', 'Show all']
             ],
             buttons: [
                 'pageLength', 'csv', 'pdf', 'print'
             ],
             language: { search: "" },
             select: true
         }
     );
     $(".dataTables_filter input").addClass("search-input");
     $(".dataTables_filter input").attr('placeholder', 'Search');
     $('#my_list')
         .removeClass('display')
         .addClass('table table-striped table-hover');</script>

Views/Owners/Create.cshtml
@model Accommodation.Models.Owner

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Owner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IDNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nationality, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nationality, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nationality, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AltContactNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AltContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AltContactNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Owners/Delete.cshtml
@model Accommodation.Models.Owner

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Owner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IDNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nationality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AltContactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AltContactNumber)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Owners/Details.cshtml
@model Accommodation.Models.Owner

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Owner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IDNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nationality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AltContactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AltContactNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ownerID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Owners/Index.cshtml
@model IEnumerable<Accommodation.Models.Owner>

@{
    ViewBag.Title = "Index";
}

<h2>My Details</h2>

<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IDNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.AltContactNumber)
        </th>
        <th class="col-md-4">
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th>Actions</th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.FullName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LastName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.IDNumber)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Type)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Phone)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Status)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FileName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.AltContactNumber)
    </td>

    <td>
        <button id="btnShowModal" type="button"
                class="btn btn-sm btn-default pull-left col-lg-11 button button4">
            Pay Subscription
        </button>

    </td>


</tr>
    }


    <div>
        @*<h2 style="background-color: Yellow;color: Blue; text-align: center; font-style: oblique">Satyaprakash Bootstrap PopUp</h2>*@
        <fieldset>
            <legend style="color:orangered"></legend>
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">

                        @*<button id="btnShowModal" type="button"
                                class="btn btn-sm btn-default pull-left col-lg-11 button button4">
                            Satya Modals
                        </button>*@

                        <div class="modal fade" tabindex="-1" id="loginModal"
                             data-keyboard="false" data-backdrop="static">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">
                                        </button>
                                        <h4 class="modal-title">Subscription Details</h4>
                                    </div>
                                    <div class="modal-body">
                                        <h5>
                                            To keep us up and function:<p> 
                                            <p> One Building - R200 </p>
                                            <p> Two - Five Buildings - R950 </p>
                                            <p> Six - Ten Buildings - R1800 </p>
                                            <p> Eleven and More - R12000</p>
                                        </h5>
                                    </div>
                                    <div class="modal-footer">
                                        @Html.ActionLink("Confirm and Accept Payment", "OnceOff", "Owners", new { @class = "btn btn-primary button button4" })
                                        <button type="button" id="btnHideModal" class="btn btn-primary button button4">
                                            Hide
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </fieldset>
    </div>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">

    </script>
    <script src="bootstrap/js/bootstrap.min.js"></script>

    <script type="text/javascript">

        $(document).ready(function () {
            $("#btnShowModal").click(function () {
                $("#loginModal").modal('show');
            });

            $("#btnHideModal").click(function () {
                $("#loginModal").modal('hide');
            });
        });
    </script>

</table>