Models/Truck.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Accommodation.Models
{
    public class Truck
    {
        [Key]
        [Required]
        [Display(Name = "Registration Number")]
        public string TaxiID { get; set; }
        public byte[] Image { get; set; }
        [Required]
        [ForeignKey("TruckMake")]
        [Display(Name = "Make Name")]
        public long TruckMakeID { get; set; }
        [Required]
        [ForeignKey("TruckModel")]
        [Display(Name = "Model Name")]
        public long TruckModelID { get; set; }    
        [DataType(DataType.EmailAddress)]
        [StringLength(maximumLength: 50, MinimumLength = 3)]
        [Display(Name = "Manager's Email")]
        public string CreatedBy { get; set; }
        public string landlordEmail { get; set; }
        public string PropertyAddress { get; set; }
        public virtual TruckMake TruckMake { get; set; }
        public virtual TruckModel TruckModel { get; set; }
    }
}

Controllers/TrucksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Accommodation.Models;
using Microsoft.AspNet.Identity;

namespace Accommodation.Controllers
{
    public class TrucksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Trucks
        public ActionResult Index()
        {
            var trucks = db.Trucks.Include(t => t.TruckMake).Include(t => t.TruckModel);
            return View(trucks.ToList());
        }
        public ActionResult TruckRequest()
        {
            var trucks = db.Trucks.Include(t => t.TruckMake).Include(t => t.TruckModel);
            return View(trucks.ToList());
        }
        // GET: Trucks/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Truck truck = db.Trucks.Find(id);
            if (truck == null)
            {
                return HttpNotFound();
            }
            return View(truck);
        }

        // GET: Trucks/Create
        public ActionResult Create()
        {
            ViewBag.TruckMakeID = new SelectList(db.TruckMakes, "TruckMakeID", "MakeName");
            ViewBag.TruckModelID = new SelectList(db.TruckModels, "TruckModelID", "ModelName");
            return View();
        }

        // POST: Trucks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TaxiID,Image,TruckMakeID,TruckModelID,CreatedBy,landlordEmail,PropertyAddress")] Truck truck, HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                truck.Image = ConvertToBytes(file);
            }
            var userName = User.Identity.GetUserName();
            var id = db.Managers.Where(x => x.Email == userName).Select(x => x.ManagerId).FirstOrDefault();
            var bId = db.ManagerBuildings.Where(x => x.ManagerId == id).Select(x => x.BuildingId).FirstOrDefault();
            var address = db.buildings.Where(x => x.BuildingId == bId).Select(x => x.Address).FirstOrDefault();
            if (ModelState.IsValid)
            {
                truck.PropertyAddress = address;
                truck.CreatedBy = userName;
                db.Trucks.Add(truck);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TruckMakeID = new SelectList(db.TruckMakes, "TruckMakeID", "MakeName", truck.TruckMakeID);
            ViewBag.TruckModelID = new SelectList(db.TruckModels, "TruckModelID", "ModelName", truck.TruckModelID);
            return View(truck);
        }
        public byte[] ConvertToBytes(HttpPostedFileBase file)
        {
            BinaryReader reader = new BinaryReader(file.InputStream);
            return reader.ReadBytes((int)file.ContentLength);
        }
        // GET: Trucks/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Truck truck = db.Trucks.Find(id);
            if (truck == null)
            {
                return HttpNotFound();
            }
            ViewBag.TruckMakeID = new SelectList(db.TruckMakes, "TruckMakeID", "MakeName", truck.TruckMakeID);
            ViewBag.TruckModelID = new SelectList(db.TruckModels, "TruckModelID", "ModelName", truck.TruckModelID);
            return View(truck);
        }

        // POST: Trucks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TaxiID,Image,TruckMakeID,TruckModelID,CreatedBy,landlordEmail,PropertyAddress")] Truck truck)
        {
            if (ModelState.IsValid)
            {
                db.Entry(truck).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TruckMakeID = new SelectList(db.TruckMakes, "TruckMakeID", "MakeName", truck.TruckMakeID);
            ViewBag.TruckModelID = new SelectList(db.TruckModels, "TruckModelID", "ModelName", truck.TruckModelID);
            return View(truck);
        }

        // GET: Trucks/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Truck truck = db.Trucks.Find(id);
            if (truck == null)
            {
                return HttpNotFound();
            }
            return View(truck);
        }

        // POST: Trucks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Truck truck = db.Trucks.Find(id);
            db.Trucks.Remove(truck);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Trucks/Create.cshtml
@model Accommodation.Models.Truck

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "Trucks", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h2>Truck</h2>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.TaxiID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TaxiID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TaxiID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="file" name="file" />
            @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TruckMakeID, "Truck Make", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TruckMakeID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TruckMakeID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TruckModelID, "Truck Model", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TruckModelID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TruckModelID, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Trucks/Delete.cshtml
@model Accommodation.Models.Truck

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Truck</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TruckMake.MakeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TruckMake.MakeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TruckModel.ModelName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TruckModel.ModelName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.landlordEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.landlordEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PropertyAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PropertyAddress)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Trucks/Details.cshtml
@model Accommodation.Models.Truck

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Truck</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TruckMake.MakeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TruckMake.MakeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TruckModel.ModelName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TruckModel.ModelName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.landlordEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.landlordEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PropertyAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PropertyAddress)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TaxiID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Trucks/Edit.cshtml
@model Accommodation.Models.Truck

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Truck</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TaxiID)

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TruckMakeID, "TruckMakeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TruckMakeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TruckMakeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TruckModelID, "TruckModelID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TruckModelID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TruckModelID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.landlordEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.landlordEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.landlordEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PropertyAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PropertyAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PropertyAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Trucks/Index.cshtml
@model IEnumerable<Accommodation.Models.Truck>

@{
    ViewBag.Title = "Index";
}

<h2 align="center">Truck</h2>
<a class="btn btn-default" href="@Url.Action("Create","Trucks")">
    <i class="fa fa-plus"></i>
    Add New Truck
</a>
<table class="table table-hover table-striped table-responsive" id="my_list">
    <thead>
        <tr class="table-header-row">
            <th>
                @Html.DisplayNameFor(model => model.TruckMake.MakeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TruckModel.ModelName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PropertyAddress)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TruckMake.MakeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TruckModel.ModelName)
            </td>
            <td>
                @if (item.Image != null)
                {
                    var base64 = Convert.ToBase64String(item.Image);
                    var ImgSource = string.Format("data:image/gif;base64,{0}", base64);
                    <img src="@ImgSource" width="100" height="100" />
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PropertyAddress)
            </td>
            <td>
                <a href="@Url.Action("Details","Trucks", new { id=item.TaxiID })" rel="tooltip" title="View" class="btn btn-info btn-simple btn-xs"><i class="fa fa-eye"></i></a>
                <a href="@Url.Action("Edit","Trucks", new { id=item.TaxiID })" rel="tooltip" title="Edit" class="btn btn-success btn-simple btn-xs"><i class="fa fa-edit"></i></a>
                <a href="@Url.Action("Delete", "Trucks", new { id = item.TaxiID })" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-xs"><i class="fa fa-trash"></i></a>
            </td>
        </tr>
        }
    </tbody>
</table>
<script type="text/javascript">
$('#my_list').dataTable(
         {
             dom: 'Bfrtip',
             lengthMenu: [
                 [10, 25, 50, -1],
                 ['10 rows', '25 rows', '50 rows', 'Show all']
             ],
             buttons: [
                 'pageLength', 'csv', 'pdf', 'print'
             ],
             language: { search: "" },
             select: true
         }
     );
     $(".dataTables_filter input").addClass("search-input");
     $(".dataTables_filter input").attr('placeholder', 'Search');
     $('#my_list')
         .removeClass('display')
         .addClass('table table-striped table-hover');</script>

Views/Trucks/TruckRequest.cshtml
@model IEnumerable<Accommodation.Models.Truck>

@{
    ViewBag.Title = "TruckRequest";
}

<style>
    .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        max-width: 100% !important;
        margin: auto;
        text-align: center;
        height: 160px !important;
        margin-bottom: 20px !important;
        border: groove !important;
    }

        .card:hover {
            border-radius: 10px;
            border-color: aqua !important;
        }
</style>
<h2 style="text-align:center; padding-bottom:20px !important">Available Trucks</h2>

<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-8">
                <div class="card">

                    <img class="card-img-top" src="data:image/png;base64,@Convert.ToBase64String(item.Image, 0, item.Image.Length)" style="width: 200px; height: 150px" alt="" align="left">

                    <div class="card-body" @*align="center"*@>
                        <h4 class="card-title"><strong>@Html.DisplayFor(x => item.TruckMake.MakeName)</strong></h4>
                        <h4 class="card-title"><strong>@Html.DisplayFor(x => item.TruckModel.ModelName)</strong></h4>
                        <h4 class="card-title"><strong>@Html.DisplayFor(x => item.TaxiID)</strong></h4>
                        <br />
                        <p><a class="btn btn-default" onclick="location.href='@Url.Action("Create","RequestTrucks", new { id=item.TaxiID})'">Request Truck &raquo;</a></p>
                    </div>
                    </div>
                </div>
            }
    </div>
</div>